name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: hooria-ahmed
          outputs: |
            dist/github-contribution-grid-snake-purple.svg?palette=github-dark-purple
            dist/github-contribution-grid-snake-purple.gif?palette=github-dark-purple

      - name: Push snake files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
